version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"  # Відкриваємо порт для PHP-сервера
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=monorail.proxy.rlwy.net
      - DB_PORT=53676
      - DB_DATABASE=railway
      - DB_USERNAME=postgres
      - DB_PASSWORD=yBvUgaqtraIRooWftLCLkGtjCFzYuonj
    volumes:
      - .:/var/www/html
    command: php -S 0.0.0.0:8000
