version: '3.8'

services:
  php-apache:
    build: .
    container_name: php_server
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    env_file: 
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
